### ISSUE TITLE
Support for FastAPI

### ISSUE THREAD

**Issue by arnonmoscona** [getappmap/appmap-python#145]
Currently remote recording is supported for Django and Flask. It would be nice to have a FastAPI integration as well.

**Comment by ptrdvrk** [comment]
Thank you for the ticket, @arnonmoscona. We'll add FastAPI to the appmap-python backlog. What sort of services are you building with FastAPI?

**Comment by arnonmoscona** [comment]
In my particular situation we're doing knowledge management and provide internal APIs for query and inference. We also plan on using it for internal tooling UI (in combination with HTMX and Jinja templates)
