### ISSUE TITLE
vscode pytest discovery fails after pip install appmap

### ISSUE THREAD

**Issue by IvoLeist** [getappmap/appmap-python#196]
Hello appmap developers,

I have seen your pitch on TechCrunch and thought I give it a try :rocket: 

The generated app maps definitely look cool and are quite helpful.
Well done !

However, unfortunately I stumbled about some issues. 
The most annoying for me right now is that since I have installed appmap (`pip install appmap`)
the vscode pytest discovery for testing our flask app  fails (see error message below)
*after deinstalling (`pip uninstall appmap`) the pytest discovery works again as expected.

> ./venv/bin/python ~/.vscode/extensions/ms-python.python-2022.18.2/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir . -s --cache-clear tests
> cwd: .
> [ERROR 2022-11-1 11:52:5.883]: Error discovering pytest tests:
>  n [Error]: [2022-12-01 11:52:05,035] INFO appmap._implementation.detect_enabled: AppMap recording is enabled because will record by default.
> 
>     at ChildProcess.<anonymous> (/home/ivo/.vscode/extensions/ms-python.python-2022.18.2/out/client/extension.js:2:242843)
>     at Object.onceWrapper (node:events:646:26)
>     at ChildProcess.emit (node:events:526:28)
>     at maybeClose (node:internal/child_process:1092:16)
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) 

    
 
Some information about my system:
> Pop!_OS 22.04 LTS x86_64 

Python (3.10.6)
> appmap==1.12.4
> pytest==7.2.0
> pytest-cov==3.0.0
> Flask==2.0.3
> Flask-Cors==3.0.10
> Flask-Migrate==4.0.0
> Flask-SQLAlchemy==2.5.1
> flask-restx==0.5.1

vscode:

> Version: 1.73.1
> Commit: 6261075646f055b99068d3688932416f2346dd3b
> Date: 2022-11-09T03:54:53.913Z
> Electron: 19.0.17
> Chromium: 102.0.5005.167
> Node.js: 16.14.2
> V8: 10.2.154.15-electron.0
> OS: Linux x64 6.0.6-76060006-generic
> Sandboxed: No
 
 Let me know if you would need more information about it :v:

**Comment by apotterri** [comment]
Hi @IvoLeist, thanks so much for trying AppMap!

Thanks, too, for the comprehensive bug report. I'll try to reproduce your issue, and let you know what I find.

**Comment by IbrahimAH** [comment]
I had to use Test Explorer in our project to discover and run tests until this is fixed 
Name: Test Explorer UI
Id: hbenl.vscode-test-explorer
Description: Run your tests in the Sidebar of Visual Studio Code
Version: 2.21.1
Publisher: Holger Benl
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer

my vscode settings.json contains these lines for our tests stored in a /tests folder
```
  "python.testing.pytestArgs": [
    "tests"
  ],
  "testExplorer.useNativeTesting": true,
  "pythonTestExplorer.testFramework": "pytest", // overrides testing.pytestEnabled setting
```

**Comment by apotterri** [comment]
@IvoLeist I believe the problem you reported has been fixed in a recent version of `appmap-python`. Can you try upgrading to 1.13.1 and seeing if pytest test discovery works for you, please?

**Comment by apotterri** [comment]
@IbrahimAH Thank you, too, for trying AppMap!

Can you provide some more detail about the problem you're having, please? The version of `appmap-python` you're using, what you expected would happen, what actually happened, and any errors you saw would all be very helpful.

Thanks again.

**Comment by IvoLeist** [comment]
@apotterri yes I can confirm that now the pytest discovery no longer fails using 
**appmap==1.13.1**

Thank you for letting me know :)

**Comment by IbrahimAH** [comment]
Hey @apotterri, thanks for the quick reply. 1.13.1 seems to have fixed the problem for me too. Thanks for the help. If i see any issues in the future I'll post the full log, but this issue looks to be resolved now.

**Comment by apotterri** [comment]
@IvoLeist @IbrahimAH Thanks to you both for confirming that 1.13.1 has fixed your problems. I'll close this issue, but feel free to open a new one if you have any further trouble.

You're also most welcome to join us in Slack: https://appmap.io/slack .
