### ISSUE TITLE
Python doesn't record by default for unittest.

### ISSUE THREAD

**Issue by symwell** [getappmap/appmap-python#197]
I made a couple of [simple tests](https://github.com/symwell/try_appmap_python) with `pytest` and `unittest` expecting to see AppMap generate AppMaps.

It turns out AppMap wasn't recording tests by default for `unittest`. For `unittest` it needs `import appmap.unittest` as shown [here](https://github.com/symwell/try_appmap_python/blob/master/program_unittest.py#L3).  I added this import because I had seen this import in the documentation.

It shouldn't be necessary for the user to import anything in the tests, since AppMap is supposed to be recording by default.

This issue should:
- make AppMap record by default for `unittest`
- update the docs to not suggest `import appmap.unittest`

Until this gets fixed, if you're trying AppMap with `unittest` change your tests to do `import appmap.unittest`.

Note it records by default with `pytest`.

The fix may be related to https://github.com/getappmap/appmap-python/issues/194.

**Comment by symwell** [comment]
I have a [fix ](https://github.com/getappmap/appmap-python/commit/2a2fd8efad357f826602479a57eef47f9dbca749) on [branch](https://github.com/getappmap/appmap-python/compare/sw/record_by_default_for_unittest?expand=1) `sw/record_by_default_for_unittest`.

I verified this fix makes `unittest` record by default through the Appmap hello world [repo](https://github.com/symwell/try_appmap_python).

The fix [fails](https://app.travis-ci.com/github/getappmap/appmap-python/jobs/590272074) the testcase `test_configuration.py::TestDefaultConfig::test_not_created_if_missing_and_not_enabled`.

The fix doesn't fail this testcase when integrated in [branch](https://github.com/getappmap/appmap-python/compare/sw/improve_environment_detection_for_python__detect_enabled_in_env?expand=1) `improve_environment_detection_for_python__detect_enabled_in_env`.

**Comment by brikelly** [comment]
@apotterri @symwell is this still an issue?

**Comment by apotterri** [comment]
Yes. I realized this morning, though, that it will be fixed by my changes for #194 (which should be up for review this afternoon).
