### ISSUE TITLE
`ModuleNotFoundError: No module named 'importlib_metadata'`

### ISSUE THREAD

**Issue by symwell** [getappmap/appmap-python#210]
[Slack](https://applanding.slack.com/archives/C02DU9210Q2/p1673107752052949)
[log](https://portal.azure.com/#view/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222023-01-07T16%3A04%3A02.81Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222023-01-07T16%3A04%3A02.81Z%22))%20and%20session_Id%20%3D%3D%20%2252ef39dc9fb2875524b0ec4e469817f6440d89c2f976224e1c7f4734c37c9770%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%2Cexception%3DcustomDimensions%5B%22appmap.debug.exception%22%5D%7C%20project-reorder%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog%2Cexception)

```
Running command: `python3 --version`

Python 3.7.1


Running command: `python3 -c "import sys; print(sys.prefix)"`

Error processing line 1 of C:\Users\TEST\AppData\Roaming\Python\Python37\site-packages\appmap.pth:

Traceback (most recent call last):
File "C:\Program Files\Python37\lib\site.py", line 168, in addpackage
exec(line)
File "<string>", line 1, in <module>
File "C:\Users\TEST\AppData\Roaming\Python\Python37\site-packages\appmap\__init__.py", line 2, in <module>
from _appmap import generation # noqa: F401
File "C:\Users\TEST\AppData\Roaming\Python\Python37\site-packages\_appmap\__init__.py", line 1, in <module>
from . import configuration
File "C:\Users\TEST\AppData\Roaming\Python\Python37\site-packages\_appmap\configuration.py", line 14, in <module>
import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```

**Comment by apotterri** [comment]
There's not enough info here to know what went wrong, and the telemetry has aged out.
