### ISSUE TITLE
Load labeling config

### ISSUE THREAD

**Issue by symwell** [getappmap/appmap-python#213]
Add in `appmap-python` the ability to read a configuration file that contains labels.

`appmap-ruby` contains configuration files containing labels for built-ins [here](https://github.com/getappmap/appmap-ruby/tree/master/lib/appmap/builtin_hooks) and functions and common [gems](https://github.com/getappmap/appmap-ruby/tree/master/lib/appmap/gem_hooks).

**Comment by symwell** [comment]
As far as I can tell, `appmap-python` already contains some [label configs](https://github.com/getappmap/appmap-python/tree/master/appmap/labeling) and a facility that [loads and instruments](https://github.com/getappmap/appmap-python/blob/master/_appmap/configuration.py#L346) functions.

**Comment by dividedmind** [comment]
Should this be closed? Seems it's already implemented.

**Comment by symwell** [comment]
> Should this be closed? Seems it's already implemented.

I don't know.  @apotterri said there's something that needs to be done that he's working on before loading the labeling config can be implemented.  I formed the impression label configs are already being loaded.

So I'm confused.
