### ISSUE TITLE
First GET request in oscar-django takes ~2mins to process

### ISSUE THREAD

**Issue by symwell** [getappmap/appmap-python#223]
Sarah reports:

When I run this workflow the project builds fine
```
$ git clone https://github.com/django-oscar/django-oscar.git
$ cd django-oscar
$ virtualenv --python=python3 oscar
$ source ./oscar/bin/activate
(oscar) $ make sandbox
(oscar) $ sandbox/manage.py runserver
```

When I add in an install for appmap before or after make sandbox the server doesnt start
```
(oscar) $ make sandbox
(oscar) $ pip install appmap
(oscar) $ sandbox/manage.py runserver
```
-- 

On a quick look the first request takes ~2mins to process on Django's [get_response](https://github.com/getappmap/appmap-python/blob/master/appmap/django.py#L239) and 31secs on [after_request_hook](https://github.com/getappmap/appmap-python/blob/master/appmap/django.py#L251).

![Image](https://user-images.githubusercontent.com/111290954/217655840-c137f2ed-a9ae-4539-b167-7d2b0925cf14.png)

**Comment by apotterri** [comment]
Sorry, I didn't follow up in the Slack thread, but I got to the bottom of this. There was one method that was getting call ~100K times in processing that request. Once we excluded it, the server worked fine, and generated decent AppMaps.
