### ISSUE TITLE
Installing with Python 3.12 throws a long, ugly error

### ISSUE THREAD

**Issue by Daniel-Warner-X** [getappmap/appmap-python#270]
Evidently AppMap doesn't install properly using Python 3.12. It leaves the user in this confusing state where the install process throws and error, but the onboarding steps turn green and progress.

![image](https://github.com/getappmap/appmap-python/assets/1229326/994bb969-8e1d-48df-8f18-f47072dd5718)

**Comment by apotterri** [comment]
Fixed by #274 .
