### ISSUE TITLE
Non-JSON serializable types throw an error when recorded with AppMap

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-python#283]
Non-JSON serializable types can cause the application to panic.

```txt
FAILED tests/test.pt - TypeError: Object of type int64 is not JSON serializable
1 failed, 29 passed, 39 warnings in 10.53s
```

```txt
_appmap/generation.py:114: in default
    return json.JSONEncoder.default(self, o)
```

via https://appmap-group.slack.com/archives/C03GM7D2QRH/p1708366829827279

https://github.com/getappmap/appmap-python/issues/312

**Comment by apotterri** [comment]
Rather than adding a special case for `int64` to `AppMapEncoder`, we need to figure out a better way of handling unknown types.

Maybe something like
```python
try:
    return json.JSONEncoder.default(self, o)
except TypeError:
    return repr(o) # or maybe str(o)
```

It would probably be good if the tests for this fix include some sort of simple app that uses `numpy`.
