### ISSUE TITLE
Disable the agent by default

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-python#294]
The VSCode extension seems to run Python commands which trigger log files to fill up the root of the project directory.

We either need to disable logging by default, or disable it under this specific circumstance.

From a user:
> It keeps creating appmap.yml and pollutes my working directory with myriad of appmap.logs.

**Comment by apotterri** [comment]
It's probably not just logging we want to disable, but all processing in the agent, i.e. running as if `APPMAP=false` were in the environment.

There are several cases it would be good to detect: this one, when running an python installer (`pip`, `poetry`, `pipenv`, etc), and when running the Python Language Server.

**Comment by apotterri** [comment]
After some discussion, it actually seems like it would be better to disable the agent by default. We'll provide a runner script that would enable it. So, for example, a Flask app could be run as:

```shell
$ appmap flask --app app --debug run -p 8080
```
and you'd get the previous behavior (code gets instrumented, remote and request recording are enabled).

**Comment by kgilpin** [comment]
As long as this is somehow compatible with the many users out there who are doing it the old way and may still be using an older agent version.

**Comment by kgilpin** [comment]
In this suggestion what is `appmap` ? Is it the AppMap downloadable binary? Or a Python wrapper script? In which case we would need it to not cause a name collision.

**Comment by kgilpin** [comment]
Can you explain the discussion and why the conclusion was reached to move in the direction of a launch command?

**Comment by apotterri** [comment]
> In this suggestion what is `appmap` ? Is it the AppMap downloadable binary? Or a Python wrapper script? In which case we would need it to not cause a name collision.

It's a python wrapper script. It can be named whatever's appropriate, `appmap` was just the first thing that came to mind.

**Comment by apotterri** [comment]
> I don’t think we can just change it from being enabled by default to requiring an env var in all cases. This will be too sudden and incompatible for existing users when they upgrade their agent.

Just to clarify, the requirement will be that they either set the env var **or** that they use the runner script.

But, if doing either of those seems too incompatible, what would you suggest?

**Comment by apotterri** [comment]
And, just to be clear, I thought I was making the change that the rest of the group was asking for. If that's not the case, I'm happy to look for alternative solutions.
