### ISSUE TITLE
In "seaborn" project, many tests fail with "is not JSON serializable"

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-python#312]
An example from https://github.com/mwaskom/seaborn/issues/3664

```
pip install -e .
pip install numpy pytest appmap
make test
```

FAILED tests/_core/test_properties.py::TestLineStyle::test_mapping_from_dict[num] - TypeError: Object of type int64 is not JSON serializable

**Comment by apotterri** [comment]
This is a dup of https://github.com/getappmap/appmap-python/issues/283 .
