### ISSUE TITLE
bad AppMaps generated

### ISSUE THREAD

**Issue by apotterri** [getappmap/appmap-python#341]
There is some circumstance (or maybe more than one) under which the agent generates an AppMap with an incorrect structure.

This appears to be related to an exception being thrown when an HTTP request is processed. The simplest example we've found so far appears to be https://github.com/getappmap/vscode-appland/blob/d9b9c325edb40791d94353ccd3541baab1d241fa/test/fixtures/workspaces/project-external-service/tmp/appmap/external_service_example.appmap.json, but there are others listed in https://github.com/getappmap/appmap-js/issues/1824

**Comment by zermelo-wisen** [comment]
These AppMaps seems to break this rule: Parent call of a return event is the closest preceding, not yet matched call event in the event array.

They create this incorrect structure with their event order in events array:
```
┌─── call #1
│┌─── call #2
└┼── ret #3
 └─── ret #4
```

Instead of this:
```
┌── call #1
│ ┌── call #2
│ └── ret #3
└── ret #4
```

**Comment by zermelo-wisen** [comment]
An AppMap can be checked with this script:

```python
import argparse
import json


def check(events):
    stack = []
    for e in events:
        if e["event"] == "call":
            stack.append(e)
        elif e["event"] == "return":
            if len(stack) > 0:
                call = stack.pop()
                if call["id"] != e["parent_id"]:
                    return f"Unbalanced call.id:{call['id']} != return.parent_id:{e['parent_id']} return.id:{e['id']}"
            else:
                return "Unbalanced"
    if len(stack) == 0:
        return "Balanced"
    else:
        return "Unbalanced"


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Check if AppMap events are balanced.")
    parser.add_argument("file", type=str, help="Path to AppMap JSON file")
    args = parser.parse_args()

    with open(args.file, "r", encoding="UTF8") as f:
        data = json.load(f)
        events = data["events"]

    result = check(events)
    print(result)

```
