### ISSUE TITLE
`django.test.TestCase` not recorded when the tests are run by pytest

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-python#363]
`paperless-ngx` uses `django.test.TestCase` for its tests. `django.test.TestCase` is a subclass of `unittest.TestCase` that adds functionality for testing Django applications.

 When running these test cases with `appmap-python`, no AppMaps are emitted. It seems as though the subclasses of `django.test.TestCase` are not treated equally to those of `unittest.TestCase`.

**Comment by kgilpin** [comment]
@dustinbyrne can you provide more information to help Navie spec this issue? Then apply the label `navie-plan`.

**Comment by apotterri** [comment]
paperless uses pytest to run Django tests. This isn't a usual configuration for a django project. The pytest plugin provided by `appmap` doesn't currently support this configuration, so no test recordings get created.

**Comment by evlawler** [comment]
@apotterri so the process would be to either make a new issue and then specify it based on your comments above and add any additional context you would like to provide and if I understand correctly, Navie will regenerate the plan.  Alternatively you could just edit Dustin's comments above and it will kick off again and you can see if it is more correctly scoped.

**Comment by dustinbyrne** [comment]
This states that Django uses unittest, so shouldn't that work?
https://docs.djangoproject.com/en/5.0/topics/testing/overview/

Is the issue that the import is `django.test.TestCase` and not `unittest.TestCase`?
